apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: armelab/client


