apiVersion: v1
kind: Service
metadata:
  name: client-home
spec:
#define which pod represented by service
  selector:
    app: bpel
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

