apiVersion: v1
kind: Service
metadata:
  name: armel-credit
spec:
#define which pod represented by service
  selector:
    app: credit
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: home
spec:
#define which pod represented by service
  selector:
    app: armel-home
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

